version: '3.8'

services:
  postgres:
    container_name: mini_sena_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=mini_sena
  pg-admin:
    image: dpage/pgadmin4:6
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=user
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
